"""
Evaluation Metrics for Document OCR & LLM-oriented Page Recognition
Based on IEEE Access 2025: "Development of OCR Service for Page-Level Recognition for Camera-Captured Document Images"
Section VI: OCR Evaluation Metrics for LLMs
- Edit Distance (ED) and Character Error Rate (CER)
- Text-Block ROUGE-L (TBR-L) based on Longest Common Subsequence (LCS) over block permutations
"""

import re
import itertools
from typing import List, Tuple, Optional

def clean_for_evaluation(text: str) -> str:
    """
    Cleans text by removing special characters and preserving alphanumeric tokens,
    as specified in Section X of the IEEE Access paper.
    """
    # Keep alphanumeric characters and whitespace
    cleaned = re.sub(r'[^a-zA-Z0-9\s]', ' ', text)
    # Collapse multiple whitespaces
    cleaned = re.sub(r'\s+', ' ', cleaned).strip().lower()
    return cleaned

def compute_levenshtein(s1: str, s2: str) -> Tuple[int, int, int, int]:
    """
    Computes Levenshtein edit distance and counts of insertions, deletions, substitutions.
    Returns (distance, insertions, deletions, substitutions).
    """
    m, n = len(s1), len(s2)
    dp = [[0] * (n + 1) for _ in range(m + 1)]
    
    for i in range(m + 1):
        dp[i][0] = i
    for j in range(n + 1):
        dp[0][j] = j
        
    for i in range(1, m + 1):
        for j in range(1, n + 1):
            if s1[i - 1] == s2[j - 1]:
                dp[i][j] = dp[i - 1][j - 1]
            else:
                dp[i][j] = 1 + min(
                    dp[i - 1][j],    # deletion
                    dp[i][j - 1],    # insertion
                    dp[i - 1][j - 1] # substitution
                )
                
    distance = dp[m][n]
    
    # Traceback to count operations
    i, j = m, n
    insertions, deletions, substitutions = 0, 0, 0
    while i > 0 or j > 0:
        if i > 0 and j > 0 and s1[i - 1] == s2[j - 1]:
            i -= 1
            j -= 1
        elif i > 0 and j > 0 and dp[i][j] == dp[i - 1][j - 1] + 1:
            substitutions += 1
            i -= 1
            j -= 1
        elif j > 0 and dp[i][j] == dp[i][j - 1] + 1:
            insertions += 1
            j -= 1
        elif i > 0 and dp[i][j] == dp[i - 1][j] + 1:
            deletions += 1
            i -= 1
        else:
            break
            
    return distance, insertions, deletions, substitutions

def compute_cer(pred_str: str, gt_str: str, clamp_to_gt_len: bool = True) -> float:
    """
    Character Error Rate (CER) calculation: CER = (i + d + s) / N
    N is the total number of characters in the ground truth string.
    If clamp_to_gt_len is True, limits ED to len(gt_str) to prevent penalizing extra length.
    """
    if len(gt_str) == 0:
        return 0.0 if len(pred_str) == 0 else 1.0
        
    dist, _, _, _ = compute_levenshtein(pred_str, gt_str)
    if clamp_to_gt_len:
        dist = min(dist, len(gt_str))
        
    return float(dist) / float(len(gt_str))

def lcs_words(seq1: List[str], seq2: List[str]) -> int:
    """
    Computes length of Longest Common Subsequence (LCS) between two word lists.
    O(M * N) dynamic programming implementation.
    """
    m, n = len(seq1), len(seq2)
    if m == 0 or n == 0:
        return 0
    dp = [0] * (n + 1)
    for i in range(1, m + 1):
        prev = 0
        for j in range(1, n + 1):
            temp = dp[j]
            if seq1[i - 1] == seq2[j - 1]:
                dp[j] = prev + 1
            else:
                dp[j] = max(dp[j], dp[j - 1])
            prev = temp
    return dp[n]

def compute_tbr_l(predicted_full_text: str, gt_blocks: List[str], max_permutations: int = 5040) -> float:
    """
    Computes Text-Block ROUGE-L (TBR-L) (Eq. 11 of IEEE Access 2025):
    TBR-L = max_{pi in P} LCS(F, pi(B_1, ..., B_n)) / |pi(B_1, ..., B_n)|
    
    Parameters:
    - predicted_full_text (F): Entire text script generated by the OCR system.
    - gt_blocks: List of ground-truth text block strings. Blocks composed of a single line
                 are excluded if explicitly filtered beforehand, or handled directly.
    - max_permutations: Guard limit to avoid exponential explosion for > 7 blocks;
                        uses a high-scoring greedy permutation search if n > 7.
    """
    # Clean and tokenize predicted full text
    f_cleaned = clean_for_evaluation(predicted_full_text)
    f_words = f_cleaned.split()
    if not f_words:
        return 0.0

    # Clean and tokenize ground-truth blocks
    cleaned_blocks = []
    for b in gt_blocks:
        b_clean = clean_for_evaluation(b)
        b_words = b_clean.split()
        if len(b_words) > 1: # Exclude single-word / single-line blocks per paper Section VI-B
            cleaned_blocks.append(b_words)

    if not cleaned_blocks:
        # Fallback if all blocks are small
        for b in gt_blocks:
            w = clean_for_evaluation(b).split()
            if w:
                cleaned_blocks.append(w)

    if not cleaned_blocks:
        return 0.0

    n_blocks = len(cleaned_blocks)
    total_gt_words = sum(len(b) for b in cleaned_blocks)
    if total_gt_words == 0:
        return 0.0

    best_lcs = 0

    if n_blocks <= 7:
        # Exact permutation search
        for perm in itertools.permutations(range(n_blocks)):
            perm_words = []
            for idx in perm:
                perm_words.extend(cleaned_blocks[idx])
            val = lcs_words(f_words, perm_words)
            if val > best_lcs:
                best_lcs = val
    else:
        # Greedy heuristic alignment for large number of blocks
        remaining_blocks = list(range(n_blocks))
        ordered_blocks = []
        # Order blocks according to appearance of their first tokens in f_words
        f_joined = " ".join(f_words)
        def block_pos(idx):
            first_words = " ".join(cleaned_blocks[idx][:min(3, len(cleaned_blocks[idx]))])
            pos = f_joined.find(first_words)
            return pos if pos != -1 else 10**8
            
        remaining_blocks.sort(key=block_pos)
        perm_words = []
        for idx in remaining_blocks:
            perm_words.extend(cleaned_blocks[idx])
        best_lcs = lcs_words(f_words, perm_words)

    return float(best_lcs) / float(total_gt_words)
